### ISSUE TITLE
Is there any way to get Sequence instead of Iterable from exposed queries?

### ISSUE THREAD

**Issue by vforvoid** [JetBrains/Exposed#1013]
First of all, thank you for this awesome library, I like it a lot.

As far as I can see `Table.selectAll()` returns a `Query`, which is a subtype of `Iterable`. Which in turn means Exposed allocates the memory for all the items in my table before returning query result. I've tested it on a dummy table with 100k values and `selectAll()` got me an `ArrayList` with all the values. That mean that eventually I will get Out Of Memory exception when my table is going to be big enough if I'm about to use this method.

Well, I'm not using `selectAll`, but even when I select by a set of primary key values using `table.id inList idList` I'm getting an Iterable, while I'd prefer to deal with Sequences if it is possible.

Is there any way I can get a Sequence from Exposed?
Thanks in advance.

**Comment by Tapac** [comment]
Hi @vforvoid, the problem is that (AFAIK) most of jdbc drivers still load all result sets in memory.
If you look into [`Query.iterator()`](https://github.com/JetBrains/Exposed/blob/f41753bb94b139ad0bd84538489ed8b8b4866fc8/exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Query.kt#L213) implementation Exposed tries to load ResultRows in `on-demand` maner, so you could use `selectAll().asSequence()`.
