### ISSUE TITLE
Is it possible to perform a join on a List?

### ISSUE THREAD

**Issue by danielwarddev** [JetBrains/Exposed#1027]
I have two `ArrayList<Int>`s that I want to join to a `Query`. Is this possible? I am currently using `inList`, but it is not returning the same results as an inner join. The reason is that with an inner join, there are some duplicate values that exist in my result set, all of which get joined. However, I cannot do this with the list - with duplicate values, the size of the list is over 4000, and since each one of these counts as a parameter, I surpass the TSQL paramter limit of 2100, so I call a distinct() on the list. Here is an example of what I'm doing:

``` kotlin
val query = Table1.join(Table2, JoinType.INNER, additionalConstraint = { Table1.field = Table2.field })
		  .select{(Table1.otherField inList list1.distinct()) and
		          (Table2.otherField inList list2.distinct())}
```

and here is an example of what I'm hoping to do:

``` kotlin
val query = Table1.join(Table2, JoinType.INNER, additionalConstraint = { Table1.field = Table2.field })
		  .join(list1.ToTable(), JoinType.INNER, additionalConstraint = { Table1.field = list1.field }
		  .join(list2.ToTable(), JoinType.INNER, additionalConstraint = { Table2.field = list2.field }
```

**Comment by bog-walk** [comment]
@danielwarddev I'm not sure what performing a join on multiple lists best translates to in plain SQL, so if you know the ideal SQL statement that produces the results you require, please share.

Exposed does provide `joinQuery()` to chain a join on a select statement, so something like this is possible:
```kt
Table1.join(Table2, JoinType.INNER, additionalConstraint = { Table1.field = Table2.field })
    .joinQuery(on = { Table1.field = Table2.field }) { Table1.select { Table1.otherField inList list1 }
    .joinQuery(on = { Table1.field = Table2.field }) { Table2.select { Table2.otherField inList list2 }
```

If `joinQuery()` is not the solution you need and it turns out that the solution is something currently unsupported, like CTEs or table value constructors, please consider opening a feature request on [YouTrack](https://youtrack.jetbrains.com/newIssue?project=EXPOSED&c=Type%20Feature&draftId=25-4449790) with an example of your use case and the plain SQL solution, so that we can investigate its implementation and any workarounds for you.
