### ISSUE TITLE
 SchemaUtils.createMissingTablesAndColumns produces incorrect SQL CREATE statement if column has "." in name

### ISSUE THREAD

**Issue by planerist** [JetBrains/Exposed#1041]
I'm trying to use columns with names like: 'foo.bar bar' (space between bar & bar)

Exposed produces CREATE statement with names like 'foo."bar bar"'. Expected behaviour '"foo.bar bar"'

If i quote column names by myself, I got another problem. Exposed produces ALTER TABLE ADD statements for each (already created) column.

**Comment by bog-walk** [comment]
@planerist A column identifier with both spaces and periods is best defined in quotes to ensure that the identifier sent to the database is an exact match.

I can confirm that on version 0.45.0, quoting the column name `"\"foo.bar bar\""` results in the expected behavior `"foo.bar bar"` and does not result in any ALTER statements being generated.
