### ISSUE TITLE
incorrect type inference for Java Time

### ISSUE THREAD

**Issue by SchweinchenFuntik** [JetBrains/Exposed#1080]
kotlin: 1.4.10
exposed: 0.28.1
NewInference and use IR - nothing affects

```kotlin
object Data : Table() {
    val datetime = datetime("date_time")
    // other
}

val from = LocalDate.of(2020, 10, 20)
val to = from.withMaxTimeOfDay // custom fun

transaction {
    Data.select { Data.datetime.between(from, to) } // not error compiler
    Data.select { Data.datetime.between<Any, OffsetDateTime>(from, to) } // IDEA: add explicit type arguments
}
```

Or is it better to write to the Kotlin bug tracker?

**Comment by Tapac** [comment]
@SchweinchenFuntik , I think the problem in between function as the first one should not compile either as column type is `Column<DateTime>` and the values are LocalDates and can't be used without conversion. 
I'll look into it closer a bit later

**Comment by bog-walk** [comment]
Using current version 0.41.1, reproducing this problem throws a `java.lang.IllegalStateException` because the `LocalDate` stored in `from` doesn't match the `Data.datetime` expression of type `Column<LocalDateTime>`. I'm assuming that `to` is an `OffsetDateTime`, which will cause the same exception when attempting to do a comparison like this using `between()`.

Please reopen this issue if the lack of compiler error returns or if the type inference issue persists.
