### ISSUE TITLE
Op.TRUE/FALSE not working on SQLServer

### ISSUE THREAD

**Issue by patrick-dedication** [JetBrains/Exposed#1120]
Using `Table.BoolColumn eq Op.TRUE` works just fine with H2 but does not work with SQLServer.
The generated SQL looks like this `Table.BoolColumn = 1 = 1`
My workaround for now is `Table.BoolColumn eq booleanLiteral(true)`.
I suspect this ist because the linked Line reads `build { booleanLiteral(true) eq booleanLiteral(true) }` when it really should read `build { this eq booleanLiteral(true) }` I guess.

https://github.com/JetBrains/Exposed/blob/4acdfbdb94d9968caf11e94c9df6e1a966e19407/exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Op.kt#L23

Maybe I'll submit a pull request later.

**Comment by bog-walk** [comment]
@patrick-dedication This is a potential case of miscommunication about the original design and intention of `Op.TRUE/FALSE`. The KDocs are also misleading (maybe because of the term 'boolean operator') and I'm thinking of ways to make the intention more clear to users.

To explain, `Op.TRUE` is supposed to represent an operator that always evaluates to `true`. The use case involves any situation needing sql like `WHERE 1 = 1 AND condition_2` and there are legitimate cases for that (like queries with dynamic conditions).

`WHERE 1` or `WHERE TRUE` is commonly valid syntax, so users can take advantage of the syntax rules and use `Op.TRUE` on the right-hand side of an equality comparison. In SQL Server and Oracle this unfortunately isn't valid syntax (because of their boolean data types) , which explains the current logic in the line you linked.

Unfortunately, if this were to be changed now, any users that have been using `Op.TRUE` as intended would need to resort to a more verbose form:
```kt
fun getItems(filterPrice: Int?): List<String> {
    return ItemTable
        .slice(ItemTable.name)
        .select {
            filterPrice?.let { ItemTable.price eq it } ?: Op.TRUE
        }.map {
            it[ItemTable.name]
        }
}

// vs

fun getItems(filterPrice: Int?): List<String> {
    return ItemTable
        .slice(ItemTable.name)
        .select {
            filterPrice?.let { ItemTable.price eq it } ?: (booleanLiteral(true) eq true)
        }.map {
            it[ItemTable.name]
        }
}
```

I realize that it may not be very fair to not be able to use `Op.TRUE` in the same way for all databases, but I hope I've explained that using it on the right-hand side in those databases is actually a feature/hack. Using a boolean value on the right-hand side is one of the purposes of `booleanLiteral()` and `booleanParam()`.
