### ISSUE TITLE
Exposed-money: can't access currency and amount for nullable compositeMoney columns

### ISSUE THREAD

**Issue by hfazai** [JetBrains/Exposed#1122]
````KOTLIN
object Article : IntIdTable() {
  val name = varchar("name", 100).nullable()
  val price = compositeMoney(10, 5,"price").nullable()
}
````
cant reference the amount and currency : `Article.price.amount` because `nullable()` here returns `CompositeColumn` and not `CompositeMoneyColumn`

As a workaround we can do a cast:
````KOTLIN
object Article : IntIdTable() {
  val name = varchar("name", 100).nullable()
  val price = compositeMoney(10, 5,"price").nullable() as CompositeMoneyColumn<BigDecimal?, CurrencyUnit?, MonetaryAmount?>
}
````

Same thing for `default()` method

I suggest to make improvement so that we can manage better compositeMoney columns. @Tapac , any thoughts?

**Comment by jnfeinstein** [comment]
I've run into this as well and also used casting to fix the issue.  The issue is [here](https://github.com/JetBrains/Exposed/blob/master/exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Table.kt#L905), where we replace the column with a wrapped version that is nullable, thereby losing the composite typing.  @hfazai I have this:
```
typealias NullableMoneyColumn = CompositeMoneyColumn<*, *, MonetaryAmount?>
```
so you can do `as NullableMoneyColumn`.  I also recall the nullable generics on the composite money column being inconsistent, like sometimes you can put in nulls but not take them out or vice versa.

**Comment by hfazai** [comment]
> where we case the column as nullable, thereby losing the composite typing.

Yes indead, 

> typealias NullableMoneyColumn = CompositeMoneyColumn<*, *, MonetaryAmount?>

Thanks @jnfeinstein for the suggestion.

**Comment by Tapac** [comment]
It's impossible to create a generic function that will return the exact nullable type. The only possible solution is to create `nullableCompositeMoney` function. @hfazai , @jnfeinstein , what do you think?

**Comment by jnfeinstein** [comment]
@Tapac I think that masks a bigger issue with making nullable composite columns, which could have a lot of functionality as an interface.  We've already found one great use-case: querying on the included columns.

What if the composite column interface required defining `fun nullable(): C<T?>`?  This would allow the author to specify the behavior of a nullable column, which may not necessarily equate to making all included columns nullable.

**Comment by Tapac** [comment]
@jnfeinstein , thank you for the idea. That sounds like a plan. I will try to extend the CompositeColumn class with default implementation,
