### ISSUE TITLE
Comparison LocalDate (Month,..)

### ISSUE THREAD

**Issue by 456634** [JetBrains/Exposed#1162]
I think there is an issue with LocalDate.

```Kotlin
Table
     .slice(Table.value.sum())
     .select { Table.date.year() eq dateParam(LocalDate.of(2020,1,1)).year() }
     .groupBy(Table.date.month())
```
With LocalDate the result is empty.

```Kotlin
Table
     .slice(Table.value.sum())
     .select { Table.dateTime.year() eq dateTimeParam(LocalDateTime.of(2020,1,1,0,0)).year() }
     .groupBy(Table.dateTime.month())
```
With LocalDateTime it works as expected.

While troubleshooting, I noticed that LocalDate is stored as a Datatype DATE in Sqllite.
LocalDateTime, however, as TEXT. Maybe this is the problem.

Exposed Version: 0.29.1
Sqlite-jdbc: 3.34.0

**Comment by AJRego** [comment]
Hello. I have the same problem.

exposed: 0.40.1
sqlite-jdbc: 3.36.0.3

The problem with the date column is that it's stored in a format that sqlite doesn't recognize as a valid date, so all queries return null. This is very strange, because when entering data, the date is in "YYYY-MM-dd" format, but later in the database it appears as a string of integers.

Did you find any solution? I find it cumbersome to save the time in my database when I only use the date.
