### ISSUE TITLE
Binary vs Blob columns in SQL Server

### ISSUE THREAD

**Issue by FidasL** [JetBrains/Exposed#1165]
I have got `VARBINARY(MAX)` column in my database schema, so I decided to define Exposed table object like this:
```
object Person: Table("persons") {
    val id: Column<Long> = long("id").autoIncrement("persons_seq")
    val binaryColumn: Column<ByteArray?> = binary("binary_column", Int.MAX_VALUE).nullable()
}
```

I ran into a problem when trying insert row into this table without setting `binaryColumn` value (it is nullable)
```
MyTable.insert {
    it[id] = 1
}
// Or null value in binaryColumn
MyTable.insert {
        it[id] = 1
        it[binaryColumn] = null
}
```
I get this exception: `Implicit conversion from data type nvarchar to varbinary(max) is not allowed. Use the CONVERT function to run this query.`

I found out that Exposed executes this command during insert:
`INSERT INTO table_name (id, binary_column) VALUES (@P0, @P1) select SCOPE_IDENTITY() AS GENERATED_KEYS`
And all arguments except bigint and datetime are defined as nvarchar(4000):
`@P0 bigint, @P1 nvarchar(4000)`

Using `.blob()` column definition with type `ExposedBlob` instead of `ByteArray` solved this problem, but I prefer using `.binary()` column with specifying length. Is there any solution for this? What is difference between `ExposedBlob` and `ByteArray` type?

**Comment by dtbullock** [comment]
I've tracked down the problem with a minimal case:

For a table like:

```
CREATE TABLE [dbo].[test](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[bincol] [varbinary](max) NULL,
 CONSTRAINT [PK_thingtest] PRIMARY KEY CLUSTERED ([id] ASC)
```

doing:

```
DriverManager.getConnection("jdbc:sqlserver://etc...")
        .use { conn ->
            conn.prepareStatement("INSERT INTO test (bincol) values (?)").use { pstmt ->
                pstmt.setObject(1, null)
                pstmt.executeUpdate()
            }
        }
```

... produces your 'Implicit conversion from data type nvarchar to varbinary(max)` error.

However, if you instead do:  `pstmt.setBytes(1, null)`, it succeeds.  This sort of makes sense ... it's impossible to do any type inference on a null ... so the JDBC driver apparently just guesses instead of looking up its internal metadata about the table.

Here's the relevant code from the MS JDBC Driver (1 level deep from their implementation of `PreparedStatement#setObject(int,Object)`)

```
if (null == obj) {
            // If the JDBC type of the parameter is UNKNOWN (i.e. this is the first time the parameter is being set),
            // then use a JDBC type the converts to most server types with a null value.
            if (JDBCType.UNKNOWN == targetJDBCType)
                targetJDBCType = JDBCType.CHAR;
```
... but `varbinary(max)` is not a type which a `CHAR` will 'implicitly convert to'.  (Hence the error).


Exposed falls prey to this behaviour, because to set values other-than BLOBs call, it ultimately does:

```
statement.setObject(index, value)   // JdbcPreparedStatementImpl.kt line 26 (Exposed 0.1.29)
```

So every time a nullable Exposed field has been set explicitly to `null`, because `setObject(int,Object)` is ultimately called, the JDBC driver will choose 'CHAR' as the JDBC type of the field and hope it can be implicitly converted.  According to [this authoritative chart](https://docs.microsoft.com/en-us/sql/t-sql/functions/cast-and-convert-transact-sql?view=sql-server-ver15#implicit-conversions), that will succeed in every case *except* where the target type is `BINARY` or `VARBINARY` or `TIMESTAMP`!  

If we allow that the error is correct about `NVARCHAR` instead of simply `CHAR` ... because of some other implicit conversion in the bowels of the system ... then `IMAGE` is also not allowed as a target type, but Exposed doesn't promise to support that type, so it's no big deal in that case.

**Comment by Tapac** [comment]
Fixed in master.
