### ISSUE TITLE
Database closing after each transaction making it very slow

### ISSUE THREAD

**Issue by PvdBerg1998** [JetBrains/Exposed#123]
Please give me an option to disable this functionality and handle the connection myself.

**Comment by Tapac** [comment]
@PvdBerg1998 , just use any connection pool which will handle it for you. In most cases .close() just returns connection to pool.

**Comment by PvdBerg1998** [comment]
Could you give me any guidance on how to achieve this? Thanks for the quick response.

**Comment by Tapac** [comment]
You might try to take HikaryCP, look at [this example](https://github.com/brettwooldridge/HikariCP#initialization) (it is Java, but I think it's easy to convert to Kotlin) and then, after you set up HikariDataSource, just call: `Database.connect(dataSource)` with it, instead of `Database.connect(jdbcUrl,...)`

**Comment by PvdBerg1998** [comment]
Thanks! I have another question: can I update a table without a where clause?
Maybe I can use the replace function, but I can't get it to work. I really hope this library gets some documentation because it's hard to work with atm.

**Comment by Tapac** [comment]
You can subscribe to  #115 issue, I think it will be fixed soon. 
Lack of documentation is also known ( #39 , #87 ) problem, but we don't have enough time to make it 😢 
Any PRs are very welcome!
