### ISSUE TITLE
decimalLiteral results ArithmeticException: Rounding necessary

### ISSUE THREAD

**Issue by HanikLZ** [JetBrains/Exposed#1270]
```
val decimal = BigDecimal("1.11")
val decimalLiteral = decimalLiteral(decimal)
```
code like this, but within decimalLiteral function
```
/** Returns the specified [value] as a decimal literal. */
fun decimalLiteral(value: BigDecimal): LiteralOp<BigDecimal> = LiteralOp(DecimalColumnType(value.precision(), value.scale()), value.setScale(1))
```

the scale of decimal value was be set to 1, if decimal's scale greater than 1,  then ArithmeticException : Rounding necessary will be throw

**Comment by bog-walk** [comment]
This issue was fixed by [this commit](https://github.com/JetBrains/Exposed/commit/a3af52444862281f8953552769769decfbd55d1c#diff-e20a5c458ef36c376c73157d76c31c6d8e45817774d210526969cd0c3df12c3a), so `ArithmeticException` is no longer thrown for inserted values with scale > 1 in current version 0.43.0.

If there are any further issues with `DecimalColumnType` or literals, please consider reporting them on [YouTrack](https://youtrack.jetbrains.com/newIssue?project=EXPOSED&draftId=25-4442763).
