### ISSUE TITLE
wrapAsExpression<LocalDateTime>

### ISSUE THREAD

**Issue by Hell-Hope** [JetBrains/Exposed#1372]
java.sql.Timestamp cannot be cast to java.time.LocalDateTime

`object ATable{
    val createDateTime = datetime("create_date_time")
}`
createDateTime is java.time.LocalDateTime

**Comment by Tapac** [comment]
Can you please share a more complex example and/or stacktrace as I can't see `wrapAsExpression` in your code?

**Comment by bog-walk** [comment]
Please consider reopening this issue on [YouTrack](https://youtrack.jetbrains.com/newIssue?project=EXPOSED&draftId=25-4442763) if the problem still persists. If you do so, please also provide the details requested above, as well as how you are attempting to insert/cast data, so that we can attempt to assist you properly.
