### ISSUE TITLE
DAO Update Example

### ISSUE THREAD

**Issue by ChasDouglass** [JetBrains/Exposed#140]
Could I get an example of updating a row when using the DAO model?

Adv-thanks-ance

**Comment by Tapac** [comment]
What row do you want to update? Can you clarify what exactly do you want to update?

**Comment by ChasDouglass** [comment]
Silly me.

I was looking for a "User.set()" or "User.update".   I found
"Users.update()" which does what I want.

It would be nice if the single page of documentation included an update
example.

Thanks!

**Comment by lnhrdt** [comment]
I found the API confusing in the same way. It's strange that the DAO layer provides the ability to INSERT via `User.new{ ... }` but it does not provide a way to UPDATE. I have to drop down to the SQL DSL layer to update a record.

It feels like it would be natural for the DAO layer to provide the ability to UPDATE records. Thoughts?

**Comment by oshai** [comment]
It is actually possible to update via DAO. See example here: https://github.com/JetBrains/Exposed/wiki/DAO#update

**Comment by lnhrdt** [comment]
Wow thank you for showing me that @oshai! That's probably more what @ChasDouglass was looking for here.

Do you know if it possible to update multiple columns in one commit?

**Comment by oshai** [comment]
I think it is not possible, but  @Tapac can confirm.

**Comment by lnhrdt** [comment]
@oshai from what I've seen so far I don't think it is possible either, thanks for confirming.

@Tapac I'd like to propose something like this for the DAO update API:

```kotlin
// existing method
val user: User = User.new {
    name = "a"
    city = stPete
    age = 5
}

// new method (proposal)
val updatedUser: User = User.update({ Users.id eq user.id }) {
    name = "A"
    age = 10
}
```

With the most important distinction from `Users.update(...) { ... }` in the SQL DSL is the return type. The proposal above returns `User` and the update method in the SQL DSL always returns `Int`.

Or is there some value I don't see yet in forcing users to use the SQL DSL for updates?

**Comment by oshai** [comment]
I think that the update should be on the entity itself and not as a "static" method (similar to apply)

**Comment by lnhrdt** [comment]
I considered that at first, but then observed that it would require a superfluous SELECT in many instances. For example when you have a record's ID and the desired updates, but not an instance of the current record. You would have to fetch the entity, before updating it. This scenario most often comes up for me when responding to a RESTful PUT request.

Why do you think the update method should be on the instance rather than the class? Perhaps both a class and an instance method are warranted.

**Comment by oshai** [comment]
I think the way you suggest is very similar to the DSL api: https://github.com/JetBrains/Exposed/wiki/DSL#update and I don't see an advantage for adding it.

**Comment by lnhrdt** [comment]
Perhaps what I've suggested isn't the right solution but I still think there's something missing from the overall API with regards to updates. Specifically:
1. The DSL update method returns an Int. I see an advantage in having an update method that can update multiple columns and return the new record.
2. The fact that you can only update columns one at a time using the DAO layer seems like a big oversight. I see an advantage in making the existing DAO update mechanism performant.

**Comment by oshai** [comment]
I agree although I mostly use DSL. I suggest something like this:
`
val updatedUser: User = userBeforeUpdate.update {
    name = "A"
    age = 10
}`

**Comment by Tapac** [comment]
@oshai , @lnhrdt, Exposed doesn't make an immediate update when you set a new value for Entity, it just store it on the inner map. "Flushing" values to database occurs at the end of transaction or before next "select *" from database.

So you work with entities in way you work with any other objects with mutable fields in Kotlin/Java, you may change them in loops, change different entities in same function, etc.

```Kotlin
val cities = City.all().toList()
val users = User.all().toList()
cities.forEach { city ->
   city.name = city.name + "!!!"
   users.filter { it.city = city }.forEach { user ->
       user.name = user.name + " from " + city.name
   }
}
```

**Comment by lnhrdt** [comment]
@Tapac wow, thanks for clarifying that! That's a big difference. This makes the way I've been doing error handling a little dangerous because if some exception were thrown due to an invalid update it wouldn't be thrown until later lines of code. I'll do some refactors and see how I like it, now that I understand what's really happening. If I have more thoughts after doing some refactors I'll be sure to share them.

To anyone stumbling in to this thread: ignore all of my misguided ideas above. 😆
