### ISSUE TITLE
Can Exposed be used in quarkus

### ISSUE THREAD

**Issue by jian-sun** [JetBrains/Exposed#1506]
Can Exposed be used in quarkus/reactive application

**Comment by bog-walk** [comment]
Historically there have been some [H2-related](https://github.com/JetBrains/Exposed/issues/919) [issues](https://github.com/JetBrains/Exposed/issues/1197) with using Exposed + Quarkus, but they have been [resolved](https://github.com/JetBrains/Exposed/commit/cd6bb936b339bc0a55d2ae59ba71f027ea8d0504).
So the answer is yes to Quarkus (and with [GraalVM](https://github.com/JetBrains/Exposed/issues/713) native image). However, not so much to the reactive side, as Exposed does not currently support a Reactive API. The latter is a long-standing issue on the roadmap that will be addressed.

If you do (or have been) using them together, please don't hesitate to report any limitations/issues on [YouTrack](https://youtrack.jetbrains.com/newIssue?project=EXPOSED&draftId=25-4442763), so that we can attempt to further assist you.

**Comment by BierDav** [comment]
Is there a guid/sample or so how to implement exposed in quarkus correctly? I mean where to initialize the Database, how to manage transactions and so on. The classical use cases.
