### ISSUE TITLE
EntityID as Number

### ISSUE THREAD

**Issue by dummyco** [JetBrains/Exposed#1597]
Hello! Thank you for that amazing framework.
Is there a way to get an underlying number (long) column expression from `EntityID` provided by `LongIdTable`?
For instance, to implement id-based shuffling with a modulo:
`AnyTable.id mod shuffleSeed`

**Comment by Tapac** [comment]
Do you mean SQL `mod` not kotlin one?

**Comment by dummyco** [comment]
@Tapac yes! So, at the end of the day, to have the ability to write something like that:

```
.orderBy(
    MyTable.id mod seed to SortOrder.ASC,
    MyTable.id to SortOrder.ASC
)
```

**Comment by AlexeySoshin** [comment]
@dummyco 
I think this should be already supported:
```kotlin

.orderBy(
    Expression.build { MyTable.id mod seed } to SortOrder.ASC,
    MyTable.id to SortOrder.ASC
)
```

**Comment by dummyco** [comment]
@AlexeySoshin it seems like `ModOp` is expecting `<T : Number?, S : Number?>` expressions, but `EntityID` does not satisfy it

**Comment by AlexeySoshin** [comment]
After looking at the code some more, my comment above is incorrect, and what you need is `rem` operator, not `mod` operator. 
As you correctly point out, `ModOp` executes mod operation in the database, and that's what you want.

The reason `ModOp` doesn't work with `EntityID` is because the type is tight at the moment:
https://github.com/JetBrains/Exposed/blob/9b561b02971b13e7445aa37223dbfabfd419d14b/exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Op.kt#L313

We could either loosen the type, which may result in runtime errors, or we may introduce another `ModOp` for a specific case of `EntityID<Number?>`

I attached a draft PR for that.

**Comment by dummyco** [comment]
@AlexeySoshin, thank you for looking into it and posting a PR. The solution with separate `EntityID`-friendly operators and `Op`-s sounds good. I wonder if Exposed should have this support for all the numeric (and maybe not only numeric but any applicable) operations to a type, wrapped by `EntityID`. Maybe even some sort of a generic approach that would allow Exposed to unwrap the `EntityID` type and apply all the standard ops. Thinking out loud 😅

**Comment by Tapac** [comment]
Different mod/rem operations with EntityID columns are support since 0.41.1
