### ISSUE TITLE
 Duplicate column name in table

### ISSUE THREAD

**Issue by douglasqueirozalmeida** [JetBrains/Exposed#1646]
Am I doing something wrong when using the `IdTable` class?

Example:
```
object Users : IdTable<String>(name = "user") {
    val cpf = varchar("cpf", 11).uniqueIndex()
    val email = varchar("email", 128)
    val pass = varchar("pass", 128)
    val nome = varchar("nome", 256)
    val dtNascimento = date(
        "dtNascimento"
    )
    override val primaryKey = PrimaryKey(cpf)
    override val id: Column<EntityID<String>>
        get() = cpf.entityId()
}
```

Result: 
`Duplicate column name "cpf" in table "user"`

**exposedVersion=0.41.1**

**Comment by PoisonedYouth** [comment]
I cannot reproduce the behavior with your provided code. How do you create the schema? Maybe the creation script is adding a duplicate column.

**Comment by bog-walk** [comment]
Please reopen this issue if the problem persists.

If it does, could you also share more details about the database being used & schema creation, so we could make further attempts to reproduce the problem?

**Comment by dicosta** [comment]
Just to comment that I was having a similar same issue, so this might help someone in the future to save some time to figure out

Problem in my case was here:
```
    override val id: Column<EntityID<Int>>
       get() = integer("id").entityId()
```
Notice the use of `get() = integer("id").entityId()` instead of `= integer("id").entityId()`

In my case, table was being created correclty, but when a DAO queried the data, I was receiving the duplicate columnname error.
Probably somewhere there is a call to id property that's triggering the integer() and entityId() methods. 
They are not idempotent I guess, since the integer() call registers a new column

At least in Idea CE, if you inherit an abstract class with abstract properties, the `implement members` shortcut from the IDE, uses the template `get()  = { }` which is useful if you need some calculated value, but not in this situation
