### ISSUE TITLE
Transaction timeout does not work in SpringTransactionManager

### ISSUE THREAD

**Issue by atsutaka** [JetBrains/Exposed#1671]
I'm using Exposed with Spring Boot.

Transactions are managed using Spring's `@Transactional` .

A timeout can be set for `@Transactional` .
However, that doesn't seem to work when using Exposed's SpringTransactionManager.

for example
```
@Transactional(timeout = 3)
fun handle() {
  ...
  ...
}
```

Can you please tell me how to get the timeout to work correctly?

exposed version: 0.41.1
spring boot version: 3.0.1 (although using version 2 is not working)

**Comment by bog-walk** [comment]
@atsutaka `SpringTransactionManager` recently got [an overhaul](https://github.com/JetBrains/Exposed/blob/main/docs/BREAKING_CHANGES.md#0440), which in its best interests removes any interference from Exposed's transaction management, in favor of Spring's own transaction lifecycle. This should improve its usability, significantly reducing the backlog of issues faced by our Spring users (e.g. with nested transactions, propagation, & isolation).

Could you please confirm if the issue you're seeing with `@Transactional(timeout = ?)` still persists after upgrading to current version 0.44.0?

**Comment by atsutaka** [comment]
@bog-walk Thanks for the reply.
I checked with version 0.44.0 and it still did not work.

If the timeout works, it will improve the stability of the application.
Please improve it.

**Comment by FullOfOrange** [comment]
Timeout could not be implemented. The exact reason for this starts with [the following issue](https://github.com/JetBrains/Exposed/issues/864): Java's statement API has a query timeout, but Exposed doesn't support this API, so there was an ambiguity in implementing timeout.

The solution seems to be the following
1. implement timeout in ExposedStatement, so that Exposed transactions and Spring Transactions can be used together.
2. implement it exclusively in Spring Transaction. (not sure how)

@bog-walk @atsutaka If you have any ideas, please share them.

**Comment by bog-walk** [comment]
@FullOfOrange As a starting point, it'd be interesting to see if [setQueryTimeout](https://docs.oracle.com/javase/8/docs/api/java/sql/Statement.html#setQueryTimeout-int-) could be applied directly on the `currentStatement` of the new transaction in `doBegin()`. Some jdbc drivers might ignore this, but it would be worth testing if we can delegate the implementation solely to the driver.

Otherwise, maybe timeout can be introduced separately to the core & jdbc modules in a similar manner as `fetchSize` was implemented for `PreparedStatementApi` and `AbstractQuery`. Then SpringTM could take advantage of that.
