### ISSUE TITLE
Use not so old MySQL version for testing

### ISSUE THREAD

**Issue by YakovSirotkin** [JetBrains/Exposed#171]
Connector/MXJ seems to be abandoned in 2011 and it launches MySQL 5.5.9. InnoDB supports fulltext search only from MySQL  5.6.4, so full-text support (#64) is blocked for MySQL by this issue.

**Comment by Tapac** [comment]
@YakovSirotkin , yes, we aware about mxj mysql version, but it was the fastest way to run MySQL tests locally at that time ago. 
Actually we don't implement Fulltext support because it has not standardized syntax among DBMS (we use fulltext indeces + Exposed in production with minimum amount of extension functions and faced different limitations such as: minimal text to search, strange syntax to match multiple words and impossibility to use @ char in search).

Regardless of this I thought about moving MySQL test into docker too. Possibly we can stay with mxj for local test on 5.5 and  use docker to test 5.6/5.7/8.0.

**Comment by YakovSirotkin** [comment]
@Tapac I am trying to implement Full Text search now and I agree that it is not obvious at all. PostgreSQL can work without special index and Oracle requires synchronization after data modifications. But I think it's OK to provide some basic support. 

And yes, Docker looks like obvious choice. Maybe it's time to use TestContainers? I like embedded databases because they are much faster, but we do need docker for SQL Server, and Oracle, and probably DB2 in future.

**Comment by Tapac** [comment]
Supported tests on the latest MySQL 5.7 + jdbc driver 8.0 .16 on CI-server (and locally with `exposedDialectTestWithDocker` gradle task)
