### ISSUE TITLE
VendorDialect properties don't depend on connection attributes but it should.

### ISSUE THREAD

**Issue by mkrup** [JetBrains/Exposed#175]
Let's assume that we have one DB with two schemas.
An application has two connections (to schema1 and schema2) with different parameters.
E.g. "jdbc:h2:mem:schema1;DB_CLOSE_DELAY=-1;mode=MySQL" and "jdbc:h2:mem:schema1;DB_CLOSE_DELAY=-1".
Let's create a table T from the first connection (SchemaUtils.createMissingTablesAndColumns(T)) and then from the second.
The second operation fails.
Looks like VendorDialect#isUpperCaseIdentifiers and VendorDialect#isLowerCaseIdentifiers should not be 'static' because it may have different values for different connections inside one application.

**Comment by fgaule** [comment]
Other approach is to infer vendor from the url prefix but also analyze, in this case, the mode attribue. When you use mode=MySQL you should use MySQL dialect instead of H2.

@Tapac This issue is related to [failing tests](https://teamcity.jetbrains.com/viewLog.html?buildId=1205021&tab=buildResultsDiv&buildTypeId=KotlinTools_Exposed_Build) when trying to use H2 in both modes.

**Comment by Tapac** [comment]
@fgaule , I think that the easiest way is to make dialects simple classes, not objects, and instantiate it on every `Database.connect{}`.
