### ISSUE TITLE
Why not directly provide double type columns?

### ISSUE THREAD

**Issue by 2690522020** [JetBrains/Exposed#198]

**Comment by Tapac** [comment]
In java (and in kotlin as well) is not recommended to use double/float because of lack of precision (http://jtechies.blogspot.ru/2012/07/item-48-avoid-float-and-double-if-exact.html), so we added BigDecimal instead, but I agree that it might be not necessary in some cases. 

You always can add your own column type.

**Comment by Tapac** [comment]
Float column type was introduced in 0.10.2
