### ISSUE TITLE
Feature request: UNSIGNED column support

### ISSUE THREAD

**Issue by yukukotani** [JetBrains/Exposed#199]
The title says it all.

**Comment by Tapac** [comment]
Should it just allow to specify SQL type for columns or also asserts values when trying to update those columns?

**Comment by Mon-chi** [comment]
It's nice if assertion is implemented, but not necessary i think.

**Comment by Tapac** [comment]
In upcoming Kotlin 1.3 should be introduced support for unsigned arithmetics, I guess we'll return to that issue in that time:D

**Comment by asimaranov** [comment]
Hi! Wasn't the feature implemented?

**Comment by tallnato** [comment]
Any news regarding this?

**Comment by alfonso-eusebio** [comment]
Hi,

Thanks for this feature!
I've been playing around with it and I think at some point (JDBC interface?) the value is converted to a Long/BIGINT and you get a `com.mysql.cj.jdbc.exceptions.MysqlDataTruncation` error.

While debugging my code I can see that the `ServerPreparedQueryBindValue` for my `ulong()` column is stored as a Long and that the MysqlType is "BIGINT" (not unsigned).

Perhaps JDBC can't support this unsigned type?

Cheers,
Alfonso

**Comment by Tapac** [comment]
@alfonso-eusebio , that's strange as ulong should be mapped to "BIGINT UNSIGNED". 
Maybe the problem is that Java doesn't have a unsigned long type and JDBC could set only long.
What exact exception do you get and with which values?

**Comment by alfonso-eusebio** [comment]
Hi @Tapac,

The error that I can see is my logs is:

`com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Out of range value for column 'some_id' at row 1`

This works fine inserting `Long.MAX_VALUE.toULong()` (0x7fffffffffffffff), but throws the error with `Long.MAX_VALUE.toULong() + 1u` (0x8000000000000000), all the way up to `ULong.MAX_VALUE` (0xffffffffffffffff).

What happens is that the error is thrown - and in my case captured and logged - but the insert query actually works because the value is **truncated** by the driver (?), so you end up with a different value in DB than you have in the code.

I hope this helps.

Cheers

**Comment by bog-walk** [comment]
[Unsigned columns](https://github.com/JetBrains/Exposed/blob/main/exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/ColumnType.kt#L243) have been supported since version [0.26.1](org.jetbrains.kotlinx.binary-compatibility-validator).

Regarding the `MysqlDataTruncation` error, if this issue persists with current version 0.41.1, please consider reporting it on [YouTrack](https://youtrack.jetbrains.com/newIssue?project=EXPOSED&draftId=25-4442763) with any updated details or use-cases.
