### ISSUE TITLE
java.sql.SQLDataException: Cannot determine value type from string 'NO'

### ISSUE THREAD

**Issue by ongky5et** [JetBrains/Exposed#251]
Dear Exposed Team,

I've got this error while running createMissingTablesAndColumns (MySql version is 5.7.21)
**

> java.sql.SQLDataException: Cannot determine value type from string 'NO'

**

Maybe it is caused by the 'it.getBoolean("IS_NULLABLE")'. the field value of 'IS_NULLABLE' column is 'NO', whereas the it.getBoolean expect a boolean value.

![image](https://user-images.githubusercontent.com/17350987/36361423-47b1dca4-155e-11e8-8d0e-6d1468b4e418.png)

![image](https://user-images.githubusercontent.com/17350987/36361408-1cb56b06-155e-11e8-81fd-3a4a018c0797.png)

![image](https://user-images.githubusercontent.com/17350987/36361453-8b8d5318-155e-11e8-9bf1-25b2dbcaf2ef.png)

Thank you

**Comment by Tapac** [comment]
Which version of jdbc driver do you use? Because at mysql-jdbc 5.1.44 there is a conversion from string to boolean inside `ResultSet.getBoolean() ` function.

Besides, we don't use that code (specific for MySQL) anymore, just jdbc DatabaseMetadata, which should not throw this exception (I guess).

Release is comming this or next week.

**Comment by ongky5et** [comment]
mysql-jdbc version is 6.0.6.
Ok. Can't wait for the new release :)
Thank you
