### ISSUE TITLE
Read only transaction

### ISSUE THREAD

**Issue by lephyrius** [JetBrains/Exposed#329]
Is there a way to prevent DAO from not writing to the database at the end of a transaction?
Something like read only transactions would be nice.

**Comment by Tapac** [comment]
You can create `StatementInterceptor` implementation with `beforeCommit` function override, where you will rollback your transaction.
Don't forget to register that interceptor at the start of your transaction.

**Comment by raderio** [comment]
@lephyrius do you mean something like read only transaction in Spring?
https://vladmihalcea.com/spring-read-only-transaction-hibernate-optimization/
https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/transaction/annotation/Transactional.html#readOnly--

**Comment by bog-walk** [comment]
If the objective is to declare a transaction as being read only and to disallow write operations, Exposed offers a `readOnly` property that can be set either as a default in `DatabaseConfig` or on a transaction-by-transaction basis (as one of the `transaction()` parameters).

If the `readOnly` mode is not feasible because the intention is to "perform" write operations without actually writing to the database, then there is the `StatementInterceptor` approach with a `transaction.rollback()`, as previously mentioned, for both DSL and DAO.
Another alternative for DAO would be to call `entityCache.clear(flush = false)` at the end of a transaction.
