### ISSUE TITLE
Misuse possibility of a EntityID constructor

### ISSUE THREAD

**Issue by jeiea** [JetBrains/Exposed#397]
```kotlin
object ATable : IntIdTable() {
  val parent = reference("parent", ATable).nullable()
}

class A(id: EntityID<Int>) : IntEntity(id) {
  var parent by ATable.parent
}

fun foo() {
  transaction { A.new {
    parent = EntityID(null, ATable) // misuse
    parent = null // correct use
  }}
}
```

I think we need to add a javadoc comment to the constructor or make internal if it is for internal use. Is it reasonable?

**Comment by Togrias** [comment]
Wait, EntityID isn't just meant for internal use, is it?

For example, say I write a function: findByIds(ids: Collection<EntityID<ID>>) so it wouldn't be inconceivable that I need to create my own EntityID to add to the list of inputs.

I always thought finding by EntityID<ID> is "safer" than finding by ID because one can check at runtime that it's the correct table.

**Comment by Tapac** [comment]
@jeiea , there are still exist cases when you need to construct EntityID, but I agree that it's somewhat unnatural to provide `null` as `id` in that case. So I think that we can make nullable constructor as private/internal and create public constructor with non-null `id` value. 

@Togrias , 
>I always thought finding by EntityID is "safer" than finding by ID because one can check at runtime that it's the correct table.
Sorry, but that had never worked like that in a searches:D `table` mostly used in equals to distinguish ids from different tables/entities and to check references.

**Comment by bog-walk** [comment]
Closing as current version 0.41.1 does not allow null `id` values in public constructor of `EntityID`.
