### ISSUE TITLE
Column needs to implement Comparable to be referenced

### ISSUE THREAD

**Issue by jedrz** [JetBrains/Exposed#409]
I've just wanted to test the fix for #398 but I came up yet another problem. In our project we created a wrapper column concept (for `String` and `Long`) that a raw column value is automatically wrapped in a value object when reading from db and unwrapped again to raw value when saving to db. I started to implementing a generic version that could work for every type of column but it's not very simple to do so - [here is my attempt](https://github.com/JetBrains/Exposed/compare/master...TouK:wrapper-columns?expand=1).

For example, let's say we have a token column which is a text column. The column definition:

```kotlin
val token = stringWrapperText("token", ::Token, Token::value).nullable()
```
and the `Token` class:
```kotlin
data class Token(val value: String)
```

As you can see `Token` class does not implement `Comparable` so it cannot be referenced from other table.

**Comment by Tapac** [comment]
Comparable is used as a marker interface to determine that all columns which could be referenced have "basic" types (like numbers/string), because there is no another interface which covers all that types. 
Otherwise, it will be possible to reference blobs and text what will lead to an error in SQL.

As a workaround, you may implement Comparable too:
```
data class Token(val value: String) : Comparable<Token> {
    override fun compareTo(other: Token): Int = value.compareTo(other.value)
}
```
or 
```
interface ComparableWrapper<T:Comparable<T>, E: ComparableWrapper<T, E>> : Comparable<E> {
    val value : T
    override fun compareTo(other: E): Int = value.compareTo(other.value)
} 

data class Token(override val value: String) : ComparableWrapper<String, Token>
```
Not sure that the second part of the code will work, but you can give it a try:D

**Comment by jedrz** [comment]
Thank you for the response! Yeah, I think I'll need to introduce an additional interface as you suggested.
