### ISSUE TITLE
skip locked support

### ISSUE THREAD

**Issue by ukarim** [JetBrains/Exposed#427]
It would be good to have support of SKIP LOCKED

**Comment by Flaflo** [comment]
I agree, would be very important

**Comment by toefel18** [comment]
I need this in production and I have problems with it, any workarounds?

**Comment by michail-nikolaev** [comment]
Also, probably `SELECT FOR SHARE` and `NOWAIT ` are required.

**Comment by williamboxhall** [comment]
We also had a situation where this would have been useful

**Comment by FedrBodr** [comment]
@williamboxhall i am found extension function on github, i try and all compile ok, but not tested yet) 
`
/**
	 * `SELECT ... FOR UPDATE SKIP LOCKED`
	 *
	 * this is handy extension function that can be applied to any table (which is a [FieldSet]
	 *
	 * Usage:
	 * ```
	 * QuickQuartzJobDetails
	 * .selectForUpdateSkipLocked { (QuickQuartzJobDetails.jobName like "$prefix%") }
	 * .map { it.toJob() }
	 * ```
	 */
	inline fun FieldSet.selectForUpdateSkipLocked(where: SqlExpressionBuilder.() -> Op<Boolean>): Query =
		selectForUpdateSkipLocked(SqlExpressionBuilder.where())

	/**
	 * this creates an instance of our custom [SkipLockedQuery]
	 */
	fun FieldSet.selectForUpdateSkipLocked(where: Op<Boolean>): Query = SkipLockedQuery(this, where)

	/**
	 * Query implementation that tacks on a `for update skip locked` to the original query
	 */
	open class SkipLockedQuery(set: FieldSet, where: Op<Boolean>?) : Query(set, where) {
		override fun prepareSQL(transaction: Transaction): String {
			val sql = super.prepareSQL(transaction)
			return "$sql for update skip locked"
		}
	}
	`

Look at this source
https://github.com/salesforce/quick-quartz/blob/master/src/main/kotlin/com/salesforce/zero/quickquartz/QuickExposed.kt

**Comment by bog-walk** [comment]
`SKIP LOCKED` and `NOWAIT` have been supported since version [0.41.1](https://github.com/JetBrains/Exposed/blob/main/docs/ChangeLog.md#0411) as part of [the sealed class](https://github.com/JetBrains/Exposed/blob/main/exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/Default.kt#L885) `ForUpdateOption`.

[Sample use](https://github.com/JetBrains/Exposed/blob/main/exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/postgresql/PostgresqlTests.kt)

If there are any issues concerning the implementations, please consider reporting them on [YouTrack](https://youtrack.jetbrains.com/newIssue?project=EXPOSED&draftId=25-4442763).
