### ISSUE TITLE
Make columns nullable by default

### ISSUE THREAD

**Issue by dahliasalem** [JetBrains/Exposed#442]
It becomes extremely verbose to label every table property as nullable via `.nullable()`. It would be a lot better to have all properties as nullable by default and distinguish the non-null ones via `.notnull()`or something along those lines. This would align us with how it is done in the postgres/sql definitions. Thanks

**Comment by Tapac** [comment]
I think that this is a too huge broken change and we'll not go for this. But I will discuss it with my colleagues.

**Comment by FRQDO** [comment]
Given that _Exposed_ is, in simple terms, _databases with Kotlin_, and given that types in Kotlin are by design _non-nullable unless explicitly stated otherwise_, I would expect any Kotlin framework to behave in the same way.

----

Maybe a good compromise would be the addition of a global flag `columnsImplicitlyNullable` that could be set if a strong alignment with SQL-like syntaxes is desired. 

This flag could then become the default value for an additional `nullable` param in `Column` constructors.
In this way, `val columnName = columnbuilder("Column Name")` would be identical to `= columnbuilder("Column Name").nullable()` if that flag is unset, and identical to `= columnbuilder("Column Name").notnull()` if it is set.
As an alternative to `columnbuilder("Column Name").notnull()` you could then also write `columnBuilder("Column Name", nullable = false)`.

Adding in this flag and optional argument should not break the API while rendering it more convenient for users like @dahliasalem.

**Comment by Tapac** [comment]
@FRQDO, it's impossible to regulate kotlin type-system with a flag. `columnbuilder` function should return either nullable or not-null value.

**Comment by FRQDO** [comment]
Ah, I see. Too much python recently… sorry.
