### ISSUE TITLE
Fix Long instead of Int

### ISSUE THREAD

**Issue by raderio** [JetBrains/Exposed#451]
`limit` method has `n` and `offset` parameters value as `Int` but should be in `Long`.
Also `count` method return result as `Int` but should be in `Long`.

**Comment by SackCastellon** [comment]
Changing the return type of `count()` from `Int` to `Long` and the type `offset` in `limit()` from `Int` to `Long` can be feasible, because it is possible to have more values in a DB than you can count with an `Int`. However, changing the type of `n` in `limit()` makes no sense because in Java lists you can only access values in positions lower than `Int.MAX_VALUE`

See:
- https://docs.oracle.com/javase/8/docs/api/java/util/Collection.html#size--
- https://docs.oracle.com/javase/8/docs/api/java/util/List.html#get-int-

PD: I tried to create a list as big as possible just for fun and I was only able to create one of size `2147483645` (`Int.MAX_VALUE = 2147483647`) in my laptop with 16GB of RAM before getting an `java.lang.OutOfMemoryError: Requested array size exceeds VM limit`, so there you go.

**Comment by AliLozano** [comment]
@Tapac Offset of `Table.deleteWhere` shouldnt be`Long` too?
