### ISSUE TITLE
Proper way to close a DB connection

### ISSUE THREAD

**Issue by Cydhra** [JetBrains/Exposed#454]
I am working on a project, that always keeps a database connection open in the background. However, the user might chose to switch to another database file. When that happens, I simply initiate a new connection using 
```Kotlin
Database.connect(...)
```

Unfortunatelly, the application deterministically runs into an issue, where the first transaction after creating the new database connection is executed on the old connection. I was not able to reproduce this issue in a minimal example, so it might have something to do with my multithreaded application (However, the new connection and the transaction afterwards are executed sequentially).

If I run
```Kotlin
transaction {
   flushCache()
}
```
before initializing the new connection, this issue does not turn up (since flushCache is also executed on commit, this is why only the first transaction after the new connection is executed on the old connection). During the initialization of the new database connection, no other transaction is running, I made sure.

So, since I was unable to reproduce the origin of this problem: How can I properly close the old connection before initializing a new one? 

Edit:
by the way, I am using
Exposed 0.11.2
Kotlin 1.3.0
H2 Driver 1.4.197

**Comment by DavidRigglemanININ** [comment]
I'm also looking for a way to close a connection, although for different reasons. I'm using the H2 database with encryption. If the password is bad, it doesn't throw any exception on the connect but rather on the first query that you make. The way things are currently set up, if you entered a password incorrectly multiple times, it sounds like I might be leaking connections and I don't see a way to prevent that.

**Comment by Tapac** [comment]
@Cydhra, every `Database.connect` create and register new TransactionManager associated with that `Database` instance, so you could create a memory leak if will call `connect` too often.

@Cydhra, @DavidRigglemanININ, real database connection will be instantiated only when you make some query or another database manipulations (like executing methods from SchemaUtils). Also, the connection will be closed just at the end of outer `transaction {}` block. 
But you still can call `.close()` on a `Transaction` instance to close a connection, but you won't be able to reuse connection within that transaction later.

**Comment by kylegoetz** [comment]
Responding to

>First of all, you shouldn't "keep a connection open in the backgroung",

If your DB is an Sqlite in-memory DB, then you *have to* keep the connection open in the background or you lose all your data.

**Comment by gunslingor** [comment]
Not really understanding what Exposed is intending from the reading documentation, in regards to connections. It seems it allows Database.connect without using the return from it directly on the transaction... guess it saves some space when using only one DB connection though clarity is lost... regardless connection opening and closing should probably get its own second in the docs, nothing talks about connection closing or how creating a connection without using it's return affects the hierarchy. For example:

```
    fun functionA() {
        dbConnect()
        transaction { ListOfSomething.all() }.forEach { functionB(it) }
    }
```

In the above, it took me a while to realize the forEach needed to go after {} and not within it. Now that it is written this way, correctly, its unclear where the dbConnects need to go since dbClose doesn't seem to exist... if dbClose existed, it would be obvious; What the possibilities are and how each would present a more efficient insert operation dependent on data properties would be obvious. This is important stuff, think 10 billion 2 bit tiny records vs 1000 1GB gigantic records.

**Comment by Tapac** [comment]
@gunslingor, When you call `Database.connect` you just prepare a connection descriptor, not the real connection. Please read a little bit more [here](https://github.com/JetBrains/Exposed/wiki/DataBase-and-DataSource#working-with-database-and-datasource).

**Comment by gunslingor** [comment]
Thanks and sorry, not sure how I missed that section of the docs.
