### ISSUE TITLE
[Beginner] Can't read from memory directly.

### ISSUE THREAD

**Issue by Narsil** [JetBrains/Exposed#463]
From the example in the docs I can see

```
val stPete = City.new {
            name = "St. Petersburg"
        }

println("Users in ${stPete.name}: ${stPete.users.joinToString {it.name}}")
````
Will make a new `SELECT` command to the Database.
How can I read stPete.name *without* making a new SELECT and possibly out of a transaction.

For now the workaround I found was to add a new attribute To City._name and have it as a regular String but that is hackish as hell.
Is there a way to manipulate a City object just in memory without touching the database (and finally calling `transaction{stPete.flush();}` maybe ?

Is the direction wrong ?

**Comment by Tapac** [comment]
The problem is not in the `stPete.name` but in the `stPete.users.joinToString {it.name}`. When you're trying to fetch references you have to make a select to another table with entity ID. Before this entity should be flushed to retrieve ID from a database. 
Please try to keep only: `"Users in ${stPete.name}"` and check if the additional select still occurs.

**Comment by Narsil** [comment]
Ok Actually I was doing something like

```
val stPete = transaction{
   City.new{
        ....
   }
}

println("${stPete.name}")
```

And I would get a `Not in a transaction` error.

I tried it today to get a better stacktrace, but it works now. Maybe I upgraded a version of something somewhere.

Anyhow, I'm closing the issue for now.
