### ISSUE TITLE
Spring transaction vs. Exposed transaction

### ISSUE THREAD

**Issue by harjis** [JetBrains/Exposed#712]
Hi!

I have been trying to find out if there are some differences between Spring Transactional annotation and Exposed transaction block when exposed DSL or DAO is used as persistence library. To me they seem to achieve the same thing with a bit different syntax but is there some features that the other has and the other doesn't?

```kotlin
import org.jetbrains.exposed.sql.transactions.transaction

@Service
class PostSaveService {
    fun create() {
        transaction {
            Post.new {
                name = "Post 1"
            }
        }
    }
}

import org.springframework.transaction.annotation.Transactional

@Service
class PostSaveService {

    @Transactional
    fun create() {
        Post.new {
            name = "Post 1"
        }
    }
}

```

**Comment by Tapac** [comment]
The main difference is that `transaction` allows you to provide additional params as `Database`, repetition attempts.
Also, `@Transaction` available only if you use Spring :D

**Comment by paulo3425** [comment]
Actually the real difference is that you can work with transaction at service level so it's a good idea use spring transaction + exposed.

**Comment by harjis** [comment]
@paulo3425 could you elaborate a bit more?

**Comment by paulo3425** [comment]
@harjis Ok. Well let's suppose we have an application that it has 3 layers (Controller, Service and Dao) inside Dao layer usually has add, update, delete and select in separates method. Ok now let's talk about service layer. Inside service layer let's suppose that we have a method called sellCar() inside that method we have more than one call to Dao layer to sell a car, because we have to check if there is a car in stock, how much it coast and other things, so now let's suppose that in middle of that operation the method sellCar() throw an exception and the method already has changed some informations that it is going to be a big problem if we do not use @Transacion at ours business layer. It's because that spring transaction is good. We can work with transaction at Services layer.

**Comment by harjis** [comment]
I don't think there is a difference in choosing weather to use `@Transactional`-annotation or `transaction`-block. To my understanding the end result is the same.

**Comment by paulo3425** [comment]
With annotation you can abstract more your class and methods.

**Comment by harjis** [comment]
I don't quite understand that that means. If you are saying that @Transactional is less intrusive as you don't need to change your actual implementation but instead spring creates a proxy where the class gets wrapped I would say I agree with that. I'm not sure though if I agree that this is a benefit

**Comment by bill-liu-0x63** [comment]
For my understanding, exposed transaction gives you some customization and simplicity over spring transaction. 

For working with multiple db(datasource). In spring, you need declare multiple datasource as Spring Beans And create jdbcTemplates for each datasource. It's lots of code. But for exposed, you write lines of Database.Connect() (a lot less code in exposed) to create multiple datasource. And you can switch db easily with transaction(db) {} no matter you are using spring or not. You can even do transaction(db1) and transaction(db2) within a function in spring service layer. 

For rollback, you need to create new runtime exception -> add rollback to annotation (e.g. @Transactional(rollbackFor = "your new runtime exception")) -> throw new runtime exception in the code. I think this logic is decent, may be some people hate it. For exposed, you just call rollback() within a transaction. I think it is better since 1 you dont need create a separate runtime exception. 2 you have less action between what causes rollback and call rollback(). (my understanding: Spring: something cause rollback -> inform spring framework -> spring framework do rollback. Exposed: something cause rollback -> user call rollback()).
