### ISSUE TITLE
Inconsistent Releases

### ISSUE THREAD

**Issue by lnryan** [JetBrains/Exposed#766]
The releases on github appear to only go up to **[0.14.1](https://github.com/JetBrains/Exposed/releases)**, where as the [bintray repository](https://bintray.com/kotlin/exposed/exposed/view#) linked in the [ReadMe](https://github.com/JetBrains/Exposed) goes up to **0.17.7** and the [Change Log]() says the versioning goes up through **0.20.2**!! ... which can be found seperately after some searching [here instead](https://bintray.com/kotlin/exposed)

Can these be adapted somehow to let them stay more in sync. 
I'd happily create a PR to bring them into consistency but it'd only last till the next change.

How about pointing the ReadMe to the Wiki Getting started instead of directly linking and updating the older `kotlin/exposed/exposed` package on bintray to alert users to the now split up libraries under `kotlin/exposed`?

**Comment by Tapac** [comment]
@lnryan , thank you for your attention. Sure, please file a PR and if you don't mind move information about wiki from the very bottom of Readme to somewhere closer to top.

**Comment by lavalamp-** [comment]
+1

I just left a comment on another (closed) ticket, and after doing some digging it looks like the issue was fixed in 18.1 (comment [here](https://github.com/JetBrains/Exposed/issues/340), resolution [here](https://github.com/JetBrains/Exposed/issues/609)).

Glad to hear that it's fixed but now I'm struggling to get the new version :laughing:

What would helping the process to get this published to a public Maven repository look like?
