### ISSUE TITLE
as of 2016-12-28: not available on maven

### ISSUE THREAD

**Issue by copans219** [JetBrains/Exposed#83]
Even though the MVN repository websites say it is there.  Here's a gradle dependency error:

* What went wrong:
Could not resolve all dependencies for configuration ':runtime'.
> Could not find org.jetbrains.exposed:exposed:0.7.4.
  Searched in the following locations:
      https://repo1.maven.org/maven2/org/jetbrains/exposed/exposed/0.7.4/exposed-0.7.4.pom
      https://repo1.maven.org/maven2/org/jetbrains/exposed/exposed/0.7.4/exposed-0.7.4.jar
  Required by:
      project :

**Comment by DrFriendless** [comment]
This is what I have in my build.gradle - you need to specify the very particular maven repository.

repositories {
    mavenLocal()
    mavenCentral()
    maven {
        url  "http://dl.bintray.com/kotlin/exposed"
    }
    maven {
        url  "http://dl.bintray.com/wasabifx/wasabifx"
    }
}

dependencies {
    compile "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
    compile "com.github.salomonbrys.kotson:kotson:2.3.0"
    compile 'org.json:json:20160810'
    compile 'org.jetbrains.exposed:exposed:0.7.4'
    compile 'mysql:mysql-connector-java:5.1.6'
    compile 'io.github.microutils:kotlin-logging:1.3.3'
    compile 'com.drfriendless:statsdb:0.1'
    compile 'org.wasabifx:wasabi:0.3.47'
    testCompile "org.jetbrains.kotlin:kotlin-test:$kotlin_version"
    testCompile 'junit:junit:4.12'
}

**Comment by oliverdain** [comment]
It'd be really nice to have this moved to the standard jcenter repo. Gradle forces you to declare all repos for all dependencies and it searches them all in order which means resolving this one will be slow as it'll have to fail on maven and jcenter first, and failing dependencies will be slower because they'll first have to fail on the custom exposed repo. Plus it clutters your build.gradle with a repo that specific to a single dependency.
