### ISSUE TITLE
select for update query

### ISSUE THREAD

**Issue by taylancapraz** [JetBrains/Exposed#837]
Hi,

As I see in source code, forUpdate() function in[ Query class ](https://github.com/JetBrains/Exposed/blob/4a59f7750736302b652590683b26a30a9afa0aa8/exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Query.kt) provides Pessimistic lock.

I don't see it in any documentation, is there a special reason for this? Is there any objection to using this function?

**Comment by Tapac** [comment]
`forUpdate` function just allows you to execute `SELECT ... FOR UPDATE`. The reason to use it or not depends on your code. Unnecessary using of `forUpdate` could lead to lock-wait/dead-lock/performance degradation, but it very helpful in a lot of cases.

**Comment by chrisjenx** [comment]
I think FOR UPDATE by default will lock associated rows via keys, wondering if there is room to expand to looser locks?

**Comment by bog-walk** [comment]
Since [version 0.40.1](https://github.com/JetBrains/Exposed/blob/main/docs/ChangeLog.md#0401), `Query.forUpdate()` accepts a `ForUpdateOption` argument that offers [flexible lock options](https://github.com/JetBrains/Exposed/blob/main/exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/ForUpdateOption.kt) depending on the database being used. In PostgreSQL, for example, all the lock strengths are supported by `ForUpdateOption.PostgreSQL`, including `FOR NO KEY UPDATE` , as well as defining the specific table(s) in which rows should be locked.

If there is a specific lock option that is still missing, which you believe is worth adding, please consider opening a feature request on [YouTrack](https://youtrack.jetbrains.com/newIssue?project=EXPOSED&c=Type%20Feature&draftId=25-4449790) with the SQL details of the lock.
