### ISSUE TITLE
Bad type on operand stack

### ISSUE THREAD

**Issue by Zhambul** [JetBrains/Exposed#85]
```
Exception in thread "main" java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    kotlin/reflect/jvm/internal/ReflectionFactoryImpl.function(Lkotlin/jvm/internal/FunctionReference;)Lkotlin/reflect/KFunction; @5: invokestatic
  Reason:
    Type 'kotlin/jvm/internal/FunctionReference' (current frame, stack[2]) is not assignable to 'kotlin/jvm/internal/CallableReference'
  Current Frame:
    bci: @5
    flags: { }
    locals: { 'kotlin/reflect/jvm/internal/ReflectionFactoryImpl', 'kotlin/jvm/internal/FunctionReference' }
    stack: { uninitialized 0, uninitialized 0, 'kotlin/jvm/internal/FunctionReference' }
  Bytecode:
    0x0000000: bb00 3b59 2bb8 0053 2bb6 0059 2bb6 005c
    0x0000010: 2bb6 0060 b700 63b0                    

	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at kotlin.jvm.internal.Reflection.<clinit>(Reflection.java:32)
	at org.jetbrains.exposed.sql.vendors.VendorDialect.<clinit>(Default.kt)
	at org.jetbrains.exposed.sql.Database.<clinit>(Database.kt:56)
```

on 
```
        init {
            registerDialect(H2Dialect)
            registerDialect(MysqlDialect)
            registerDialect(PostgreSQLDialect)
            registerDialect(SQLiteDialect)
        }

```

**Comment by Zhambul** [comment]
Sorry, guys. My bad. Used different versions of kotlin to compile

**Comment by amatkivskiy** [comment]
Hi @Zhambul , I am facing the same issue. Can you please describe what was the issue and how did you solve it? Thanks in advance 👍

**Comment by cornerkitten** [comment]
@amatkivskiy 

I ran into this same error message (`Bad type on operand stack`) while trying out Exposed. I was able to fix the issue by updating my project to use the latest version of Kotlin (currently `1.2.60`).

For my maven-based project, this was as simple as updating the `kotlin.version` in `pom.xml`, as specified by the [Kotlin tools reference](https://kotlinlang.org/docs/reference/using-maven.html). [Gradle](https://kotlinlang.org/docs/reference/using-gradle.html) and a few others are documented as well.

**Comment by metabrain** [comment]
Ok, my issue was not with Kotlin version... It was with... The import I was using for the PipelineContext extension function to replace inlining the handler for our GETs! I was using the wrong import apparently but the compiler was not complaining...

I was using 
`import io.ktor**.util.**pipeline.PipelineContext`
instead of
`import io.ktor.pipeline.PipelineContext`

As soon as I fixed that, it started working. A bit confused but yeah. Shouldn't the compiler have complained? Also, this didn't happen when running through Maven, only on the intelij unit test runner..

Hope that helps anyone with this issue
