### ISSUE TITLE
how to get raw sql execture effect raw ?

### ISSUE THREAD

**Issue by Linuxea** [JetBrains/Exposed#878]
For example:
```sql
"update user set name = 'demo' ;".execAndMap {... ...}
```
How can I get the effect of raw num when I want to know the execution result

**Comment by CHNB128** [comment]
I found solution in scope of this library. It bit ugly but work in my case.
```
transaction { // this -> Transaction
	val q = "select * from alternativetests;"
	val list = LinkedList<Map<String, Any>>()
	this.exec(q) {
		while (it.next()) {
			list.add(AlternativeTest.findById(it.getInt("id"))!!.pack())
		}
	}
}
```

**Comment by bog-walk** [comment]
As you've already seen the workaround for SQL strings in the [FAQ](https://github.com/JetBrains/Exposed/wiki/FAQ#q-is-it-possible-to-use-native-sql--sql-as-a-string) and in [#118](https://github.com/JetBrains/Exposed/issues/118), using `execAndMap` returns results from a statement that generates a `ResultSet`, like `SELECT`.

On the other hand, `UPDATE` does not return results, so using `execAndMap` as-is will execute the update but have nothing to return.

Since I'm not sure exactly what database you're using, I'll give some edge examples:

Let's say you're using PostgreSQL, you could technically get results if you append a `RETURNING` clause, but Exposed would throw an exception because it detects an update and doesn't expect a result set. To get around this, you would need to alter `execAndMap` to force Exposed to treat it like a select:
```kt
"UPDATE tester SET \"name\"='demo' RETURNING \"name\"".execAndMap { rs ->
    rs.getString("name")
}

fun <T : Any> String.execAndMap(transform : (ResultSet) -> T): List<T> {
    val result = arrayListOf<T>()
    TransactionManager.current().exec(this, explicitStatementType = StatementType.SELECT) { rs ->
        while (rs.next()) {
            result += transform(rs)
        }
    }
    return result
}
```

Now let's say you're using MySQL and your goal is to get the number of rows affected by your update statement. In this case, you could tailor a new extension function to meet these needs:
```kt
"UPDATE tester SET `name`='demo'".execUpdateAndCount()

fun String.execUpdateAndCount(): Int {
    TransactionManager.current().exec(this, explicitStatementType = StatementType.UPDATE)
    
    var count = 0
    TransactionManager.current().exec("SELECT ROW_COUNT()") { rs ->
        while (rs.next()) {
            count = rs.getInt(1)
        }
    }
    return count
}
```

Please note, as mentioned in the FAQ, that using SQL as a string is not supported fully so these are just suggested workarounds and may need to be further adjusted based on the specific SQL string operation and/or use case.
