### ISSUE TITLE
Allow index class to be extended

### ISSUE THREAD

**Issue by rockwotj** [JetBrains/Exposed#895]
Right now indexes are a data class and not able to be modified. The nice thing about columns is that I can add custom column types if I like as there is an interface. However if I want to extend this library to have custom indexes (for example https://github.com/JetBrains/Exposed/issues/585 or to be able to change to a hash index) I cannot do that.

**Comment by KubqoA** [comment]
Is there currently any way to create an index with a function? For example an index in PostgreSQL applied to lower function on the column. E.g. `create index lower_column on table (lower(column::text));`

**Comment by rockwotj** [comment]
As far as I know, there is not with Exposed. Additionally you can not extend exposed to do this either.

**Comment by vincent-cognite** [comment]
It seems that it is still not possible to apply a function when creating an index, as suggested above. Is there any plan on supporting this feature?

**Comment by bog-walk** [comment]
@rockwotj There have been 3 recently merged PRs that support: partial index in [PostgreSQL](https://github.com/JetBrains/Exposed/pull/1748) and [other databases](https://github.com/JetBrains/Exposed/pull/1763), as well as [functional index](https://github.com/JetBrains/Exposed/pull/1788), which will be available in the upcoming version. And providing index type has been supported since version [0.26.1](https://github.com/JetBrains/Exposed/blob/main/docs/ChangeLog.md#0261).

If an open/modifiable `Index` is a feature you still believe is worth adding, please consider opening a feature request on [YouTrack](https://youtrack.jetbrains.com/newIssue?project=EXPOSED&c=Type%20Feature&draftId=25-4449790), with a specific use case example so we can look further into it.
